name: Update Days Since Badge

on:
  schedule:
    - cron: '0 0 * * *'       # 每天凌晨 0 点 UTC 自动运行
  workflow_dispatch:          # 允许手动触发

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Calculate days and generate badge
        run: |
          # 起始日期（修改这里即可）
          START_DATE="2024-01-01"
          TODAY=$(date -u +%Y-%m-%d)
          DAYS_SINCE=$(( ( $(date -ud "$TODAY" +%s) - $(date -ud "$START_DATE" +%s) ) / 86400 ))

          mkdir -p output
          
          echo "{\"schemaVersion\": 1, \"label\": \"HRT\", \"message\": \"$DAYS_SINCE days\", \"color\": \"pink\"}" > output/badge.json


      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output/badge.json
          git commit -m "Update badge" || echo "No changes"
          git push
